services:
  nest-backend:
    build:
      args:
      - NODE_ENV=development
      context: nest-backend
      target: development
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./nest-backend:/app
