services:
  nest-backend:
    build:
      args:
      - NODE_ENV=development
      context: nest-backend
      target: development
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notebook
    ports:
      - 3000:3000
    volumes:
      - ./nest-backend:/app

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
